name: deploy-pages

on:
  push:
    branches: [main]
    paths-ignore:
      - "tests/**"
      - "examples/**"

env:
  BASE_URL: /${{ github.event.repository.name }}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-book:
    runs-on: ubuntu-latest

    # Recommended explicit permissions for Pages deployments
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install seqikpy
        run: |
          pip install -e .

      - name: Install dependencies
        run: |
          pip install -r ./docs/requirements.txt

      - name: Build the book
        run: |
          sphinx-apidoc -o docs/ seqikpy/
          jupyter-book build docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/_build/html"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
